import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "./components/navbar";
import GradientBackground from "./components/gradientBackground";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + "h-screen max-w-screen overflow-x-hidden no_scroll"
        }
      >
        <div className="max-w-full min-h-full relative flex flex-col items-center h-fit bg-[#000000]">
          <div className="w-full flex-1 px-4 md:max-w-[1100px]">
            <Navbar />
            <GradientBackground />
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
