import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React, { useState } from "react";
import Navbar from "./components/navbar";
import GradientBackground from "./components/gradientBackground";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className + " h-screen w-screen overflow-x-hidden"}
      >
        <div className="max-w-full min-h-full relative flex flex-col items-center h-fit bg-[#090909]">
          <div className="w-full flex-1 px-4 md:px-[200px]">
            <Navbar />
            <GradientBackground />
            {children}
          </div>
          <div className="w-full h-[250px] bg-[#0D0D0D]"></div>
        </div>
      </body>
    </html>
  );
}
